### ISSUE TITLE
Beta version format is incompatible with yarn package version resolution

### ISSUE THREAD

**Issue by FoodProduct** [NerdWalletOSS/apollo-cache-policies#31]
The current version format, `M.m.p-betaN` is not properly interpreted by yarn and so e.g. it considers `-beta9` as a newer version than `beta13` (it likely tokenizes using dashes and other non-alpha characters, then sees that the token starts with a letter and considers the whole thing a string), potentially causing incorrect versions to be installed.

**Comment by danReynolds** [comment]
Updated to stable 1.0.0+
