### ISSUE TITLE
@nerdwallet/apollo-cache-policies is not in the npm registry

### ISSUE THREAD

**Issue by jonapgartwohat** [NerdWalletOSS/apollo-cache-policies#32]
The npm package does not exist under the name specified in the README.md
```
npm install @nerdwallet/apollo-cache-policies
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nerdwallet%2fapollo-cache-policies - Not found
npm ERR! 404 
npm ERR! 404  '@nerdwallet/apollo-cache-policies@*' is not in the npm registry.
```

This one works though, but  it appears to be an older version.
https://www.npmjs.com/package/apollo-invalidation-policies

**Comment by FoodProduct** [comment]
Thanks for flagging! Seems like this only got published to NerdWallet's internal registry during the rename... cc @danReynolds

**Comment by danReynolds** [comment]
Ah sorry about that @jonapgartwohat ! When we switched it to under the @nerdwallet scope I didn't realize that defaults to private when publishing. Up now under version 1.2.1! https://www.npmjs.com/package/@nerdwallet/apollo-cache-policies
