### ISSUE TITLE
Update `react` dependency

### ISSUE THREAD

**Issue by philihp** [NerdWalletOSS/apollo-cache-policies#59]
This library has both a peer dependency of React 16.8, and also a dev dependency of React 17.0.
https://github.com/NerdWalletOSS/apollo-cache-policies/blob/master/package.json#L31
https://github.com/NerdWalletOSS/apollo-cache-policies/blob/master/package.json#L50

Any chance that the one (or both) of these could be bumped?

**Comment by danReynolds** [comment]
Sure I can bump them. Both to latest major?
