### ISSUE TITLE
Why is typescript a "dependency"?

### ISSUE THREAD

**Issue by bunkscene** [NerdWalletOSS/apollo-cache-policies#60]
I think your dependencies should be updated.  This can cause problems for consuming apps.
```
"peerDependencies": {
    "@apollo/client": "^3.4.16",
    "react": "^16.8.0"
  },
  "dependencies": {
    "graphql": "^15.5.0",
    "lodash": "^4.17.21",
    "uuid": "^7.0.3"
  },
  "devDependencies": {
    "@apollo/client": "^3.4.16",
    "@types/jest": "^25.2.3",
    "@types/lodash-es": "^4.17.5",
    "@types/react": "^17.0.19",
    "@types/graphql": "^14.5.0",
    "@types/uuid": "^7.0.4",
    "jest": "^25.5.4",
    "jest-extended": "^0.11.5",
    "prettier": "2.0.5",
    "react": "^17.0.2",
    "subscriptions-transport-ws": "^0.9.18",
    "ts-jest": "^25.5.1",
    "typescript": "^4.3.2"
  }
```

1. Removing uuidv4 because it is not used.
2. Moving @types to devDependencies
3. Moving typescript to devDependencies

**Comment by danReynolds** [comment]
Hey thanks for that change I totally agree. If you'd like to throw up a PR for that I'll happily approve. Otherwise I'll get to it in another week or so when I'm back from holiday. Thanks!

**Comment by danReynolds** [comment]
Updated in 2.7.

**Comment by bunkscene** [comment]
Awesome, thanks!  I tried to update, but got test errors locally, so I didn't want to push anything.
