### ISSUE TITLE
Not compatible with Apollo client 3.6 due to removed hooks.

### ISSUE THREAD

**Issue by smundro** [NerdWalletOSS/apollo-cache-policies#64]
```
Compiled with problems:

ERROR in ./node_modules/@nerdwallet/apollo-cache-policies/dist/hooks/useFragmentWhere.js 21:22-77

Module not found: Error: Can't resolve '@apollo/client/react/hooks/utils/useDeepMemo' 
```

**Comment by danReynolds** [comment]
Thanks for the report! Im on vacation for another 2ish weeks. Im thinking the fix here is to just copy that util into this lib or see how they’re memoizing hook post the refactor. I can look into that once im back or if anyone wants to dive in feel free
