### ISSUE TITLE
ttl doesn't seem to be working

### ISSUE THREAD

**Issue by sirpy** [NerdWalletOSS/apollo-cache-policies#78]
using the cache with a very minimal ttl, monitroing the network tab in the browser, when re issuing the query even after ttl has passed no new network calls are seen and data is fetched from cache. new queries make the network call.

**Comment by danReynolds** [comment]
Do you have some code handy? I can see how it's being configured to see if there's something that sticks out

**Comment by sirpy** [comment]
Doesn't seem to be related to your package. It seems that apollo client also doesnt re-execute the queries. maybe related to some hooks memoization.
